/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UAS1;

/**
 *
 * @author User
 */
public class Uas1 extends javax.swing.JFrame {

    /**
     * Creates new form Uas1
     */
    public Uas1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medium1txt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        originalmediumtxt = new javax.swing.JLabel();
        OriMed = new javax.swing.JTextField();
        ManggoMed = new javax.swing.JTextField();
        GreenLarge = new javax.swing.JTextField();
        CheeseMilk = new javax.swing.JTextField();
        manggomediumtxt = new javax.swing.JLabel();
        originallargetxt = new javax.swing.JLabel();
        greenteamediumtxt = new javax.swing.JLabel();
        judultxt = new javax.swing.JLabel();
        OriLarge = new javax.swing.JTextField();
        ManggoLarge = new javax.swing.JTextField();
        manggocismilktxt = new javax.swing.JLabel();
        manggolargetxt = new javax.swing.JLabel();
        greentealargetxt = new javax.swing.JLabel();
        GreenMed = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        buttonok = new javax.swing.JButton();
        totalJumlah = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        medium1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medium1txtActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5));

        originalmediumtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        originalmediumtxt.setText("Salad Original Medium");
        originalmediumtxt.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                originalmediumtxtAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        OriMed.setText("0");
        OriMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriMedActionPerformed(evt);
            }
        });

        ManggoMed.setText("0");
        ManggoMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManggoMedActionPerformed(evt);
            }
        });

        GreenLarge.setText("0");
        GreenLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenLargeActionPerformed(evt);
            }
        });

        CheeseMilk.setText("0");
        CheeseMilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheeseMilkActionPerformed(evt);
            }
        });

        manggomediumtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        manggomediumtxt.setText("Salad Manggo Medium");

        originallargetxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        originallargetxt.setText("Salad Original Large");

        greenteamediumtxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        greenteamediumtxt.setText("Salad Greentea Medium");

        judultxt.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        judultxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        judultxt.setText("SALAD MERTUA");

        OriLarge.setText("0");
        OriLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OriLargeActionPerformed(evt);
            }
        });

        ManggoLarge.setText("0");
        ManggoLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManggoLargeActionPerformed(evt);
            }
        });

        manggocismilktxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        manggocismilktxt.setText("Manggo Cheesse Milk");

        manggolargetxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        manggolargetxt.setText("Salad Manggo Large");

        greentealargetxt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        greentealargetxt.setText("Salad Greentea Large");

        GreenMed.setText("0");
        GreenMed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenMedActionPerformed(evt);
            }
        });

        total.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        total.setText("Total :");

        buttonok.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        buttonok.setText("OK");
        buttonok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonokActionPerformed(evt);
            }
        });

        totalJumlah.setText("......");

        info.setText("Masukkan jumlah makanan yang ingin dipesan pada box");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(judultxt)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(total)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(62, 62, 62)
                                .addComponent(buttonok)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(originalmediumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manggomediumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(greenteamediumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(greentealargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(manggocismilktxt)
                                    .addComponent(manggolargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(originallargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(OriMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GreenMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManggoMed, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(OriLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ManggoLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GreenLarge, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CheeseMilk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judultxt)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(OriMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(originalmediumtxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manggomediumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManggoMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(greenteamediumtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GreenMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(originallargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OriLarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(manggolargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManggoLarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GreenLarge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(greentealargetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CheeseMilk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manggocismilktxt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(111, 111, 111)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(buttonok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(totalJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medium1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medium1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_medium1txtActionPerformed

    private void buttonokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonokActionPerformed
        int totalBeli = 0;
        try {
            int saladOriginalMedium = 25000 * Integer.valueOf(OriMed.getText());
            int saladManggoMedium = 25000 * Integer.valueOf(ManggoMed.getText());
            int saladGreenteaMedium = 25000 * Integer.valueOf(GreenMed.getText());
            int saladCheeseMilk = 25000 * Integer.valueOf(CheeseMilk.getText());
            int saladOriginalLarge = 50000 * Integer.valueOf(OriLarge.getText());
            int saladManggoLarge = 50000 * Integer.valueOf(ManggoLarge.getText());
            int saladGreenLarge = 50000 * Integer.valueOf(GreenLarge.getText());
            totalBeli = saladOriginalMedium + saladManggoMedium + saladGreenteaMedium + saladCheeseMilk + saladOriginalLarge + saladManggoLarge + saladGreenLarge;
            info.setText("");
        } catch (NumberFormatException e) {
            info.setText(String.valueOf("Default pesanan harus 0 , tidak boleh kosong"));
        }
        totalJumlah.setText("Rp. "+String.valueOf(totalBeli));

    }//GEN-LAST:event_buttonokActionPerformed

    private void GreenMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreenMedActionPerformed

    private void ManggoLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManggoLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManggoLargeActionPerformed

    private void OriLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriLargeActionPerformed

    private void CheeseMilkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheeseMilkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheeseMilkActionPerformed

    private void GreenLargeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenLargeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GreenLargeActionPerformed

    private void ManggoMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManggoMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManggoMedActionPerformed

    private void OriMedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OriMedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OriMedActionPerformed

    private void originalmediumtxtAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_originalmediumtxtAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_originalmediumtxtAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
OriMed.setText("0");
ManggoMed.setText("0");
GreenMed.setText("0");


OriLarge.setText("0");
ManggoLarge.setText("0");
GreenLarge.setText("0");
CheeseMilk.setText("0");
totalJumlah.setText("......");
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Uas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Uas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Uas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Uas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Uas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheeseMilk;
    private javax.swing.JTextField GreenLarge;
    private javax.swing.JTextField GreenMed;
    private javax.swing.JTextField ManggoLarge;
    private javax.swing.JTextField ManggoMed;
    private javax.swing.JTextField OriLarge;
    private javax.swing.JTextField OriMed;
    private javax.swing.JButton buttonok;
    private javax.swing.JLabel greentealargetxt;
    private javax.swing.JLabel greenteamediumtxt;
    private javax.swing.JLabel info;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judultxt;
    private javax.swing.JLabel manggocismilktxt;
    private javax.swing.JLabel manggolargetxt;
    private javax.swing.JLabel manggomediumtxt;
    private javax.swing.JTextField medium1txt;
    private javax.swing.JLabel originallargetxt;
    private javax.swing.JLabel originalmediumtxt;
    private javax.swing.JLabel total;
    private javax.swing.JLabel totalJumlah;
    // End of variables declaration//GEN-END:variables
}
